In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [2]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

Logistic Regression

In [3]:
l_scores = cross_val_score(LogisticRegression(max_iter=400), iris.data, iris.target)
l_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [4]:
np.average(l_scores)

0.9733333333333334

Support Vector Machine

In [5]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [6]:
np.average(s_scores)

0.9666666666666666

Decision Tree

In [7]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [8]:
np.average(d_scores)

0.9666666666666668

Random Forest Classifier

In [9]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [10]:
np.average(r_scores)

0.96

The Best is For Logistic Regression